# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bunny_sim <- function(maxit, nameslist) {
    .Call(`_RcppFun_bunny_sim`, maxit, nameslist)
}

grading <- function(x) {
    .Call(`_RcppFun_grading`, x)
}

cola <- function() {
    .Call(`_RcppFun_cola`)
}

gullible <- function() {
    .Call(`_RcppFun_gullible`)
}

pancake <- function(eaten) {
    invisible(.Call(`_RcppFun_pancake`, eaten))
}

bracket <- function(master) {
    invisible(.Call(`_RcppFun_bracket`, master))
}

tictactoe <- function(TwoPlayer) {
    invisible(.Call(`_RcppFun_tictactoe`, TwoPlayer))
}

dungeon <- function() {
    invisible(.Call(`_RcppFun_dungeon`))
}

funfunc <- function(x, y, z) {
    invisible(.Call(`_RcppFun_funfunc`, x, y, z))
}

string_betrayal <- function(x) {
    .Call(`_RcppFun_string_betrayal`, x)
}

